version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: lomake_dev
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - AUTOMATIC_IAM_PERMISSIONS_ENABLED=true
    ports:
      - 8000:8000
    container_name: lomake_dev
  db:
    image: postgres:13.4
    container_name: lomake_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    container_name: lomake_db

volumes:
  pg_data:
