name: CI

on:
  push:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: Run cypress tests
        run: npm run cypress:headless

      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: toska/lomake
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: BASE_PATH=/lomake/
          tags: 'production'
