name: CI

on:
  push:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: Run cypress tests
        run: npm run cypress:headless
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: cypress
          # Directory containing files to upload
          path: /home/runner/work/lomake/lomake/cypress/

      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: toska/lomake
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: BASE_PATH=/lomake/
          tags: 'production'
          cache: true
