name: Build production image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/lomake
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: BASE_PATH=/tilannekuva/
          tags: production
