name: Test and build staging-image

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: seed db
        run: docker exec lomake_dev bash -c "node index.js seed --tokens"

      - name: Run cypress tests
        run: ./node_modules/.bin/cypress run --headless --browser firefox --spec "cypress/integration/comparison.spec.js"

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/lomake/lomake/cypress/screenshots

  build:
    name: 'Build and publish staging image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/lomake
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: BASE_PATH=/tilannekuva/
          tags: staging

  report_success:
    name: 'Report deployment success to Tilku-channel'
    runs-on: ubuntu-latest
    needs:
    - test
    - build
    if: success()
    steps:
      - name: "Send notification to Slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment
          softa-url: https://toska-staging.cs.helsinki.fi/tilannekuvalomake
          deployment-target: staging

  report_failure:
    name: 'Report test failure to Tilku-channel'
    runs-on: ubuntu-latest
    needs:
    - test
    - build
    if: failure()
    steps:
      - name: "Send notification to Slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: test-failure
